from __future__ import annotations

import json
import re
import shutil
import subprocess
import uuid
from pathlib import Path
from typing import Any

from .config import Settings
from .database import RunStore
from .manifests import ManifestError, validate_execution
from .models import DraftRecord, RunMode, RunStatus, utc_now


class DraftError(RuntimeError):
    pass


class AgentDraftService:
    def __init__(self, settings: Settings, store: RunStore, author: Any = None) -> None:
        self.settings = settings
        self.store = store
        self.author = author

    async def create_from_run(self, run_id: str, correction: str = "") -> DraftRecord:
        run = self.store.get_run(run_id)
        if run.mode != RunMode.free_query:
            raise DraftError("Only a free_query run can become an Agent draft.")
        if run.status not in {RunStatus.completed, RunStatus.inconclusive} or not run.result or not run.plan:
            raise DraftError("The free query must finish with a validated plan before drafting an Agent.")
        draft_id = f"draft_{uuid.uuid4().hex[:12]}"
        slug = f"free-query-{draft_id[-8:]}"
        draft_dir = (self.settings.draft_root / draft_id).resolve()
        if self.settings.draft_root.resolve() not in draft_dir.parents:
            raise DraftError("Draft path escaped the configured draft root.")
        query = str(run.query or "SAP free query")
        manifest = _manifest_from_run(slug, query, run.plan, correction)
        authored = {
            "content_zh": "只读 Agent 草稿。发布前必须复核业务语义、规则与证据完整性。",
            "content_en": "Read-only Agent draft. Review semantics, rules, and evidence completeness before publishing.",
            "rule_notes": ["Business owner must define deterministic completion criteria."],
        }
        author_draft = getattr(self.author, "author_draft", None)
        supports = getattr(self.author, "supports", None)
        authoring_supported = not callable(supports) or bool(supports("author_draft"))
        if callable(author_draft) and authoring_supported and run.thread_id:
            try:
                authored = await author_draft(
                    thread_id=run.thread_id,
                    query=query,
                    plan=run.plan,
                    evidence=run.result.evidence,
                    completeness=run.result.completeness.model_dump(mode="json"),
                    correction=correction,
                )
            except Exception as exc:
                raise DraftError(
                    "Codex could not author the bilingual draft content; no draft files were written."
                ) from exc
        draft_dir.mkdir(parents=True, exist_ok=False)
        (draft_dir / "agent.json").write_text(
            json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
        )
        (draft_dir / "README.md").write_text(
            _readme(slug, query, correction), encoding="utf-8"
        )
        (draft_dir / "content.zh.md").write_text(
            f"# {query[:80]}\n\n{authored['content_zh'].strip()}\n",
            encoding="utf-8",
        )
        (draft_dir / "content.en.md").write_text(
            f"# {query[:80]}\n\n{authored['content_en'].strip()}\n",
            encoding="utf-8",
        )
        fixture_dir = draft_dir / "fixtures"
        fixture_dir.mkdir()
        (fixture_dir / "validated-run.json").write_text(
            json.dumps(
                {
                    "source_run_id": run_id,
                    "query": run.query,
                    "plan": run.plan,
                    "completeness": run.result.completeness.model_dump(),
                },
                ensure_ascii=False,
                indent=2,
            )
            + "\n",
            encoding="utf-8",
        )
        test_dir = draft_dir / "tests"
        test_dir.mkdir()
        (test_dir / "test_manifest_contract.py").write_text(
            """import json\nfrom pathlib import Path\n\n\ndef test_generated_manifest_is_read_only():\n    manifest = json.loads((Path(__file__).parents[1] / 'agent.json').read_text(encoding='utf-8'))\n    assert manifest['schemaVersion'] == 2\n    assert all(step.get('readOnly', True) for step in manifest['execution']['steps'])\n""",
            encoding="utf-8",
        )
        source_dir = draft_dir / "src"
        source_dir.mkdir()
        (source_dir / "rules.py").write_text(
            """\"\"\"Business-rule skeleton generated by Agent Factory.\n\nReplace this placeholder only with deterministic, reviewable rules.\n\"\"\"\n\n\ndef evaluate(evidence: dict) -> dict:\n    return {\n        \"status\": \"inconclusive\",\n        \"reason\": \"Business rule requires owner review.\",\n        \"evidence_count\": len(evidence),\n    }\n""",
            encoding="utf-8",
        )
        (source_dir / "rule-review-notes.json").write_text(
            json.dumps(authored["rule_notes"], ensure_ascii=False, indent=2) + "\n",
            encoding="utf-8",
        )
        docs_dir = draft_dir / "docs"
        docs_dir.mkdir()
        (docs_dir / "data-contract.json").write_text(
            json.dumps(
                {
                    "schema_version": "1.0",
                    "input_schema": manifest["execution"]["inputSchema"],
                    "evidence_sources": [
                        {
                            "step_id": step["id"],
                            "executor": step["executor"],
                            "read_only": step.get("readOnly", True),
                        }
                        for step in manifest["execution"]["steps"]
                        if step["executor"] != "rule"
                    ],
                    "completeness_policy": "Never infer source_complete=true without an explicit source assertion.",
                },
                ensure_ascii=False,
                indent=2,
            )
            + "\n",
            encoding="utf-8",
        )
        draft = DraftRecord(
            draft_id=draft_id,
            run_id=run_id,
            status="generated",
            path=str(draft_dir),
            created_at=utc_now(),
        )
        self.store.save_draft(draft)
        return self.validate(draft_id)

    def validate(self, draft_id: str) -> DraftRecord:
        draft = self.store.get_draft(draft_id)
        path = Path(draft.path)
        issues: list[str] = []
        try:
            manifest = json.loads((path / "agent.json").read_text(encoding="utf-8"))
            validate_execution(manifest, str(path / "agent.json"))
            if _contains_write_operation(manifest):
                issues.append("Draft contains a write-like SAP operation.")
        except (OSError, json.JSONDecodeError, ManifestError) as exc:
            issues.append(str(exc))
        draft.status = "invalid" if issues else "validated"
        draft.validation = {"valid": not issues, "issues": issues}
        self.store.save_draft(draft)
        return draft

    def add_review_input(self, draft_id: str, review_input: str) -> DraftRecord:
        draft = self.store.get_draft(draft_id)
        if draft.status == "applied":
            raise DraftError("An applied draft can no longer be revised in the isolation directory.")
        path = Path(draft.path)
        manifest_path = path / "agent.json"
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        authoring = manifest.setdefault("authoring", {})
        authoring.setdefault("reviewInputs", []).append(review_input)
        manifest_path.write_text(
            json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
        )
        with (path / "review-notes.md").open("a", encoding="utf-8") as notes:
            notes.write(f"- {review_input}\n")
        draft.status = "generated"
        self.store.save_draft(draft)
        return self.validate(draft_id)

    def apply(self, draft_id: str) -> DraftRecord:
        draft = self.validate(draft_id)
        if draft.status != "validated":
            raise DraftError("Draft validation failed and cannot be applied.")
        manifest = json.loads((Path(draft.path) / "agent.json").read_text(encoding="utf-8"))
        target = self.settings.repository_root / "agents" / "Common" / manifest["slug"]
        if target.exists():
            raise DraftError(f"Agent target already exists: {target}")
        status = subprocess.run(
            ["git", "status", "--porcelain"],
            cwd=self.settings.repository_root,
            check=True,
            capture_output=True,
            text=True,
        )
        if status.stdout.strip():
            raise DraftError("Apply requires a clean Git worktree.")
        branch = f"codex/agent-{manifest['slug']}"
        subprocess.run(
            ["git", "switch", "-c", branch],
            cwd=self.settings.repository_root,
            check=True,
            capture_output=True,
            text=True,
        )
        shutil.copytree(draft.path, target)
        draft.status = "applied"
        draft.validation["branch"] = branch
        draft.validation["target"] = str(target)
        self.store.save_draft(draft)
        return draft


def _manifest_from_run(
    slug: str, query: str, plan: dict[str, Any], correction: str
) -> dict[str, Any]:
    title = query[:80]
    plan_copy = json.loads(json.dumps(plan))
    execution_steps = _execution_steps_from_plan(plan_copy)
    return {
        "schemaVersion": 2,
        "slug": slug,
        "module": "Common",
        "title": {"zh": title, "en": title},
        "summary": {
            "zh": "由已验证的自由 SAP 查询生成的只读 Agent 草稿。",
            "en": "Read-only Agent draft generated from a validated free SAP query.",
        },
        "status": "Draft",
        "version": "0.1.0",
        "owner": "Unassigned",
        "tags": ["Generated draft", "Read-only"],
        "sapModules": ["Common"],
        "transactions": [],
        "tables": [str(plan.get("entity_set") or "SAP OData entity")],
        "systems": ["SAP S/4HANA"],
        "inputs": {"zh": ["原始自然语言查询"], "en": ["Original natural-language query"]},
        "outputs": {
            "zh": ["执行状态", "查询源完整性", "成功数据源数量"],
            "en": ["Execution status", "Query-source completeness", "Successful source count"],
        },
        "guardrails": {
            "zh": ["严格只读；发布前必须由业务与SAP负责人复核。"],
            "en": ["Strictly read-only; requires business and SAP review before publication."],
        },
        "workflow": [
            {
                "id": "execute-validated-plan",
                "title": {"zh": "执行已验证查询计划", "en": "Execute validated query plan"},
                "description": {
                    "zh": "通过已选择的 SAP 只读 Provider 验证并执行从成功自由查询保存的 GET-only 计划。",
                    "en": "Validate and execute the saved GET-only plan through the selected SAP read Provider.",
                },
                "tools": [
                    {
                        "name": "sap_read_execute_plan",
                        "kind": "SAP Read Provider",
                        "purpose": {"zh": "执行只读 SAP 查询。", "en": "Execute the read-only SAP query."},
                    }
                ],
                "executionStepIds": [step["id"] for step in execution_steps],
            },
            {
                "id": "validate-evidence",
                "title": {"zh": "验证证据完整性", "en": "Validate evidence completeness"},
                "description": {
                    "zh": "执行本地确定性完整性规则，不访问或修改 SAP。",
                    "en": "Run the local deterministic completeness rule without accessing or changing SAP.",
                },
                "tools": [
                    {
                        "name": "evidence_summary",
                        "kind": "Local deterministic rule",
                        "purpose": {"zh": "汇总证据完整性。", "en": "Summarize evidence completeness."},
                    }
                ],
                "executionStepIds": ["validate_evidence"],
            },
        ],
        "execution": {
            "mode": "deterministic",
            "inputSchema": {
                "type": "object",
                "properties": {
                    "query": {
                        "type": "string",
                        "default": query,
                        "title": {"zh": "原始自然语言查询", "en": "Original natural-language query"},
                    }
                },
                "required": ["query"],
                "additionalProperties": False,
            },
            "steps": [
                *execution_steps,
                {
                    "id": "validate_evidence",
                    "executor": "rule",
                    "operation": "evidence_summary",
                    "inputMapping": {
                        step["id"]: f"{{{{steps.{step['id']}.output}}}}"
                        for step in execution_steps
                    },
                },
            ],
            "outputSchema": {
                "type": "object",
                "properties": {
                    "status": {"type": "string", "title": {"zh": "执行状态", "en": "Execution status"}},
                    "source_complete": {"type": "boolean", "title": {"zh": "查询源完整性", "en": "Query-source completeness"}},
                    "successful_source_count": {"type": "integer", "title": {"zh": "成功数据源数量", "en": "Successful source count"}},
                },
                "required": ["status", "source_complete", "successful_source_count"],
                "additionalProperties": False,
            },
            "outputMapping": {
                "status": "{{steps.validate_evidence.output.status}}",
                "source_complete": "{{steps.validate_evidence.output.source_complete}}",
                "successful_source_count": "{{steps.validate_evidence.output.successful_source_count}}",
            },
            "acceptance": {
                "comparisonMode": "business_semantic",
                "businessKeys": ["query"],
                "facts": ["status"],
                "metrics": ["successful_source_count"],
                "currencyAndUnitPolicy": "compare_only_when_same_or_conversion_validated",
                "requiredLimitations": ["source_completeness_not_overstated"],
            },
        },
        "authoring": {"source": "validated_free_query", "correction": correction},
    }


def _execution_steps_from_plan(plan: dict[str, Any]) -> list[dict[str, Any]]:
    if plan.get("kind") != "sap_business_agents_harness":
        return [
            {
                "id": "execute_plan",
                "executor": "sap_read",
                "operation": "execute_plan",
                "readOnly": True,
                "request": {"plan": plan},
            }
        ]
    execution_steps: list[dict[str, Any]] = []
    for index, step in enumerate(plan.get("steps") or [], start=1):
        step_id = str(step.get("id") or f"step_{index}")
        if step.get("tool") == "sap_read":
            execution_steps.append(
                {
                    "id": step_id,
                    "executor": "sap_read",
                    "operation": "execute_plan",
                    "readOnly": True,
                    "request": {"plan": step.get("plan")},
                }
            )
        elif step.get("tool") == "skill":
            execution_steps.append(
                {
                    "id": step_id,
                    "executor": "skill",
                    "operation": "execute",
                    "skillId": step.get("skill_id"),
                    "readOnly": True,
                    "request": step.get("input") or {},
                }
            )
    if not execution_steps:
        raise DraftError("The validated harness plan has no executable steps.")
    return execution_steps


def _contains_write_operation(value: Any) -> bool:
    write_terms = {"POST", "PATCH", "PUT", "DELETE", "posting", "update", "create_document"}
    if isinstance(value, dict):
        return any(
            str(child).upper() in write_terms if key in {"http_method", "method", "operation"} else _contains_write_operation(child)
            for key, child in value.items()
        )
    if isinstance(value, list):
        return any(_contains_write_operation(child) for child in value)
    return False


def _readme(slug: str, query: str, correction: str) -> str:
    return f"""# {slug}\n\nGenerated from a validated free SAP query.\n\n- Query: {query}\n- User correction: {correction or 'None'}\n- Boundary: selected SAP Provider GET-only execution\n\nReview the business semantics, input schema, output contract, completeness requirements, and deterministic rules before publishing.\n"""
