"""Business-rule skeleton generated by Agent Factory.

Replace this placeholder only with deterministic, reviewable rules.
"""


def evaluate(evidence: dict) -> dict:
    return {
        "status": "inconclusive",
        "reason": "Business rule requires owner review.",
        "evidence_count": len(evidence),
    }
